//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_QLNT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPN
    {
        public int MaDP { get; set; }
        public int MaPN { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> GiaTien { get; set; }
    
        public virtual DuocPham DuocPham { get; set; }
        public virtual PhieuNhap PhieuNhap { get; set; }
    }
}
